name: test

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Run test schedule
        run: python test_schedule.py